# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
# C964

title: Computer Science Capstone
author: Dr. Jim Ashe
logo: ./url_images/3d_regression.png
# logo: ./url_images/WGU-logo-crossed-out.png
# logo: ./_static/WGU-logo-crossed-out.png
# logo-alt-text: HELLO

# alt_text: A crossed out WGU logo. Underneath the logo a caption reads this website is NOT an official resource WGU resource! It is developed by course faculty with +20 years of experience supporting C964. 
#this doesn't work? default alt is logo
#SEE: https://github.com/pydata/pydata-sphinx-theme/pull/893
#currently shows as 'alt="logo' which sphinx default when no alt is set for the logo.https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/config.py
#also see: 

#https://github.com/executablebooks/jupyter-book/issues/1783

#https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
    - references.bib

# Add a bibtex file so that we can create citcd ..
# In _config.yml
sphinx:
  config:
    bibtex_reference_style: author_year
    bibtex_bibfiles: references.bib